name: Dependency Graph
on:
  push:
    branches:
      - main

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: dependency-graph-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # this permission is needed to submit the dependency graph

jobs:
  dependency-graph:
    name: Submit dependencies to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - uses: scalacenter/sbt-dependency-submission@v2
        with:
          modules-ignore: docs_2.12 play-functional_2.12 play-json-joda_2.12 play-json_2.12 play-functional_sjs1_2.12 play-json_sjs1_2.12
